### PR TITLE
complete sponsorship page

### PR DESCRIPTION
**Pull request by donggo-git**

### CODE REVIEW

**Review by adamseth2 — CHANGES_REQUESTED** [review]
On wide screen, because there it is not centered/ have a max width, its too wide. I would suggest just reusing the about us card components for better consistency.
image

Also font hierarchy on headers

**Comment by donggo-git** [comment]
Just change as your request, please review

**Comment by adamseth2** [comment]
Here are some changes since we are polishing the website (The numbers can ofc be tweak, they were just what I quickly changed in dev tools):

Make navbar text weight 600. Hard to see/should be bolded to since its the navbar
image

TrickFire Logo Text to make it pop even more:
font 72px, weight 700, Italic
image

Sponsorship text when fetching shows js code. Change it to something like "Deadline: ..." or "Deadline: Please Check the Form Below" so incase the javascript fails/takes a while, there is at least text
image

The About Us seems to be kinda broken?
image

The Showcase with the background pic and the description like the one below has inconsistency across the pages. For example, sponsorship text is in lowercased. I would suggest messing around with the font weight and size to make it stand out to increase font hierarchy.  
image

**Review by adamseth2 — CHANGES_REQUESTED** [review]
Needs edits above^

**Comment by adamseth2** [comment]
Really like the new photos.

The nav bar glitches out on mobile screens on ~760-~850 as I cannot close it (found it when I was split screening)
image

The sponsorship page now looks weird?
image

Other than that, ready to merge!

**Review by adamseth2 — APPROVED** [review]
looks good!

**Pull request merged**
