### PR TITLE
completed Projects page

### PR DESCRIPTION
**Pull request by agrach060**
please review

### CODE REVIEW

**Review by donggo-git — CHANGES_REQUESTED** [review]
header title margin top in responsive mode (because the nav bar stand over it)
Shorten the paragraph (optional, I haven’t figured out how to fix the issue the paragraph is too long lead break the layout)

**Comment by agrach060** [comment]
I updated the projects page according to the comments. Please review

**Review by donggo-git — CHANGES_REQUESTED** [review]
Please change the margin in the header, so that the "Project" in responsive mode, so that it won't be hidden under the navbar

**Review by donggo-git — APPROVED** [review]
Good job!

**Pull request merged**
