### PR TITLE
Adamseth2/feedback updates

### PR DESCRIPTION
**Pull request by adamseth2**
- update readme
- made Meet the Team to a team photo
- changed mechanical photo in about us to a person doing something instead
- made calendar smaller
- Fixed 767px issue on the trickfire logo glitching out (thought it was fixed but it came back??)

### CODE REVIEW

**Comment by adamseth2** [comment]
Changed media query to 767.5px and that somehow fixes the problem of the TrickFire logo glitching at 767px

**Review by VladimirKupryukhin — COMMENTED** [review]
Gotta love the 767px issue, haha.
Since you were messing around with the fonts/text stuff, I noticed that the text looks different from Chrome, Firefox, and Edge. It seems like Chrome and Edge have their text be much more bolder than Firefox? Maybe this is what people were thinking when they felt like the website was too close to their face? I remember talking about creating a scss variable to standardize the font for everything; I think this is the best course of action.

**Comment by adamseth2** [comment]
- variable for font
- fixed big calendar problem

**Comment by VladimirKupryukhin** [comment]
- Calendar height is messed up on regular sized screens - too short in height
- When flipping a phone horizontally, the calendar is too short. Consider increasing the height
- From 768px to 800px in width, the calendar, in addition to the height issues, goes slightly off screen

It seems like the main issue of the calendar being too short is due to some media query for the calendar whenever the width is above 767px

**Comment by adamseth2** [comment]
- believed I fixed the issues above

**Pull request merged**
